import { useStorage } from '@vueuse/core'
import { computed } from 'vue'

const currentLang = useStorage('locale', 'en')

const translations: Record<string, any> = {
  en: {
    nav: {
      title: 'VueHooksKit',
      docs: 'Documentation',
      hooks: 'Hooks',
      more: 'More Hooks',
    },
    hero: {
      titleLine1: 'Every Hook You Need',
      titleLine2: 'Ready to Use',
      description: 'A high-quality, type-safe Vue 3 hooks collection designed for modern web applications. Focus on building features, not utilities.',
      getStarted: 'Get Started',
      viewOnGithub: 'View on GitHub',
    },
    features: {
      items: [
        {
          title: 'Type Safe',
          description: 'Written in TypeScript with full type definitions.',
          icon: 'i-carbon-checkmark-filled',
        },
        {
          title: 'Composition API',
          description: 'Built for Vue 3 Composition API.',
          icon: 'i-carbon-code',
        },
        {
          title: 'Lightweight',
          description: 'Zero dependencies, small bundle size.',
          icon: 'i-carbon-flash',
        },
      ]
    },
    hooks: {
      title: 'Hooks Collection',
      showing: 'Showing',
      of: 'of',
      items: 'hooks',
      selectHook: 'Select a hook to view demo',
      search: 'Search hooks...',
      categories: {
        state: 'State',
        network: 'Network',
        dom: 'DOM',
        lifecycle: 'Lifecycle',
        style: 'Style',
        utils: 'Utils',
        ui: 'UI',
        data: 'Data',
        access: 'Access',
        performance: 'Performance',
        async: 'Async',
        advancedStyle: 'Advanced Style',
        errorI18n: 'Error & I18n',
      }
    },
    demo: {
      performance: {
        title: 'Performance Hooks',
        description: 'Hooks to optimize performance by reducing re-renders and unnecessary calculations.',
        memoized: 'useMemoizedFn: Function reference remains stable',
        reactive: 'useReactiveRef: Shallow ref with manual trigger',
        lazy: 'useLazyRef: Initialized only when accessed',
        clickMe: 'Click to re-render',
        childRender: 'Child Render Count:',
        mutate: 'Mutate Deeply',
      },
      async: {
        title: 'Async Hooks',
        description: 'Manage async operations with loading, error, and cancellation states.',
        execute: 'Execute',
        cancel: 'Cancel',
        status: 'Status:',
        result: 'Result:',
        error: 'Error:',
      },
      advancedStyle: {
        title: 'Advanced Style Hooks',
        hoverTitle: 'Interaction Hooks (Hover & Active)',
        hoverDescription: 'Track element hover and active states with ease.',
        scrollTitle: 'useScrollIntoView Demo',
        scrollDescription: 'Scroll an element into view smoothly.',
        hover: 'Hover me (useHover)',
        active: 'Click me (useActive)',
        scroll: 'Scroll to View (useScrollIntoView)',
        scrollTo: 'Scroll to here',
      },
      errorI18n: {
        title: 'Error & I18n Hooks',
        errorDescription: 'Catch and handle errors in child components.',
        i18nDescription: 'A lightweight internationalization hook.',
        throw: 'Throw Error',
        reset: 'Reset ErrorBoundary',
        currentLang: 'Current Locale:',
        hello: 'Hello World',
        switch: 'Switch Locale',
      },
      toggle: {
        title: 'useToggle Demo',
        description: 'A hook to toggle between two states.',
        currentState: 'Current State:',
        toggle: 'Toggle',
        setFalse: 'Set False',
        setTrue: 'Set True',
      },
      hooksDemo: {
        title: 'VueHooksKit Demos',
      },
      theme: {
        title: 'Theme Mode',
        description: 'Manage light/dark mode and system preference.',
        currentMode: 'Current Mode:',
        toggleTheme: 'Toggle Theme',
      },
      state: {
        title: 'State Management',
        counter: 'useCounter',
        counterDescription: 'A basic counter hook with min/max limits.',
        reset: 'Reset',
        storage: 'useLocalStorage',
        storageDescription: 'Persist state to LocalStorage with reactivity.',
        storagePlaceholder: 'Type here to persist...',
        storagePersist: 'Value persists across reloads:',
      },
      network: {
        title: 'Network Request',
        fetchData: 'Fetch Data',
        loading: 'Loading...',
        error: 'Error:',
      },
      utils: {
        title: 'Utils',
        debounce: 'useDebounceFn (500ms)',
        debounceDescription: 'Debounce function execution.',
        windowSize: 'useWindowSize',
        windowSizeDescription: 'Reactive window size and breakpoints.',
        clickFast: 'Click fast (multiple times)',
        width: 'Width',
        height: 'Height',
        debouncedAction: 'Debounced action executed at',
      },
      table: {
        title: 'useTable Demo',
        description: 'A powerful table hook that manages pagination, filtering, sorting, and selection logic with ease.',
        search: 'Search',
        reset: 'Reset',
        total: 'Total',
        prev: 'Prev',
        next: 'Next',
        page: '/ page',
        noData: 'No Data',
        id: 'ID',
        name: 'Name',
        role: 'Role',
        email: 'Email',
        status: 'Status',
      },
      form: {
        title: 'useForm Demo',
        username: 'Username',
        email: 'Email',
        role: 'Role',
        bio: 'Bio',
        submit: 'Submit',
        submitting: 'Submitting...',
        reset: 'Reset',
        success: 'Submitted successfully',
      },
      modal: {
        title: 'useModal & useDrawer Demo',
        description: 'Manage modal and drawer visibility and parameters.',
        openModal: 'Open Modal',
        openDrawer: 'Open Drawer',
        modalTitle: 'Modal Title',
        drawerTitle: 'Drawer Title',
        content: 'This is a modal using UnoCSS classes.',
        drawerContent: 'This is a drawer sliding from right.',
        cancel: 'Cancel',
        confirm: 'Confirm',
        close: 'Close',
        save: 'Save',
        params: 'Params:',
      },
      permission: {
        title: 'usePermission Demo',
        description: 'Fine-grained permission control for roles and actions.',
        currentRole: 'Current Role:',
        currentPerms: 'Current Permissions:',
        toggle: 'Toggle Role (User ↔ Admin)',
        visibleAll: 'Visible to everyone',
        visibleRead: "Visible if has 'read' permission (v-if)",
        visibleWrite: "Visible if has 'write' permission (v-if)",
        visibleDelete: "Visible if has 'delete' permission (class hidden)",
      },
    },
    more: {
      title: 'More Available Hooks',
      description: 'These hooks are essential utilities included in the library but do not have a dedicated demo page yet.',
      table: {
        name: 'Hook Name',
        category: 'Category',
        description: 'Description',
      },
      hooks: {
        usePagination: 'Manage pagination state with page size and total count.',
        useClickOutside: 'Detect clicks outside a target element.',
        useElementSize: 'Reactive size of an HTML element.',
        useScroll: 'Reactive scroll position of an element or window.',
        useEventListener: 'Register event listeners with automatic cleanup.',
        useSessionStorage: 'Reactive SessionStorage (same API as useLocalStorage).',
        useThrottledRef: 'Throttled reactive reference for frequent updates.',
        useGlobalState: 'Simple global state management shared across components.',
        useMounted: 'Shorthand for onMounted lifecycle hook.',
        useUnmount: 'Shorthand for onUnmounted lifecycle hook.',
        useUpdate: 'Force component to re-render.',
        useThrottleFn: 'Throttle function execution to limit frequency.',
        useTimeoutFn: 'Execute a function after a timeout with cancel support.',
        useRAF: 'Request Animation Frame hook for animations.',
        useRouteGuard: 'Vue Router navigation guard helper.',
        useBreadcrumb: 'Manage breadcrumb navigation state.',
        useResponsive: 'Responsive breakpoints helper (media queries).',
      }
    },
    footer: {
      text: 'Released under the MIT License.',
    },
  },
  zh: {
    nav: {
      title: 'VueHooksKit',
      docs: '文档',
      hooks: 'Hooks',
      more: '更多',
    },
    hero: {
      titleLine1: '你需要的每一个 Hook',
      titleLine2: '开箱即用',
      description: '专为现代 Web 应用设计的高质量、类型安全的 Vue 3 Hooks 集合。专注于构建功能，而非工具。',
      getStarted: '快速开始',
      viewOnGithub: 'GitHub 查看',
    },
    features: {
      items: [
        {
          title: '类型安全',
          description: '使用 TypeScript 编写，提供完整的类型定义。',
          icon: 'i-carbon-checkmark-filled',
        },
        {
          title: '组合式 API',
          description: '专为 Vue 3 组合式 API 构建。',
          icon: 'i-carbon-code',
        },
        {
          title: '轻量级',
          description: '零依赖，极小的打包体积。',
          icon: 'i-carbon-flash',
        },
      ]
    },
    hooks: {
      title: 'Hooks 集合',
      showing: '显示',
      of: '/',
      items: '个 Hook',
      selectHook: '选择一个 Hook 查看演示',
      search: '搜索 Hooks...',
      categories: {
        state: '状态管理',
        network: '网络请求',
        dom: 'DOM',
        lifecycle: '生命周期',
        style: '样式',
        utils: '工具',
        ui: '界面组件',
        data: '数据处理',
        access: '权限控制',
        performance: '性能优化',
        async: '异步处理',
        advancedStyle: '高级样式',
        errorI18n: '错误与国际化',
      }
    },
    demo: {
      performance: {
        title: '性能优化 Hooks',
        description: '通过减少重渲染和不必要的计算来优化性能的 Hook。',
        memoized: 'useMemoizedFn: 函数引用保持稳定',
        reactive: 'useReactiveRef: 浅层 Ref 手动触发',
        lazy: 'useLazyRef: 仅在访问时初始化',
        clickMe: '点击重渲染',
        childRender: '子组件渲染次数:',
        mutate: '深层修改',
      },
      async: {
        title: '异步处理 Hooks',
        description: '管理异步操作的加载、错误和取消状态。',
        execute: '执行',
        cancel: '取消',
        status: '状态:',
        result: '结果:',
        error: '错误:',
      },
      advancedStyle: {
        title: '高级样式 Hooks',
        hoverTitle: '交互 Hooks (Hover & Active)',
        hoverDescription: '轻松追踪元素的悬浮和激活状态。',
        scrollTitle: 'useScrollIntoView 演示',
        scrollDescription: '平滑地将元素滚动到视图中。',
        hover: '悬浮我 (useHover)',
        active: '点击我 (useActive)',
        scroll: '滚动到可视区 (useScrollIntoView)',
        scrollTo: '滚动到此处',
      },
      errorI18n: {
        title: '错误与国际化 Hooks',
        errorDescription: '捕获并处理子组件中的错误。',
        i18nDescription: '一个轻量级的国际化 Hook。',
        throw: '抛出错误',
        reset: '重置错误边界',
        currentLang: '当前语言:',
        hello: '你好世界',
        switch: '切换语言',
      },
      toggle: {
        title: 'useToggle 演示',
        description: '在两个状态之间切换的 Hook。',
        currentState: '当前状态:',
        toggle: '切换',
        setFalse: '设为 False',
        setTrue: '设为 True',
      },
      hooksDemo: {
        title: 'VueHooksKit 演示',
      },
      theme: {
        title: '主题模式',
        description: '管理亮/暗模式及系统偏好。',
        currentMode: '当前模式:',
        toggleTheme: '切换主题',
      },
      state: {
        title: '状态管理',
        counter: 'useCounter',
        counterDescription: '带最小值/最大值限制的基础计数器 Hook。',
        reset: '重置',
        storage: 'useLocalStorage',
        storageDescription: '将状态持久化到 LocalStorage 并保持响应式。',
        storagePlaceholder: '在此输入以持久化...',
        storagePersist: '值在刷新后保留:',
      },
      network: {
        title: '网络请求',
        description: '一个用于管理异步数据获取的强大 Hook。',
        fetchData: '获取数据',
        loading: '加载中...',
        error: '错误:',
      },
      utils: {
        title: '工具',
        debounce: 'useDebounceFn (500ms)',
        debounceDescription: '函数防抖执行。',
        windowSize: 'useWindowSize',
        windowSizeDescription: '响应式窗口尺寸和断点。',
        clickFast: '快速点击 (多次)',
        width: '宽度',
        height: '高度',
        debouncedAction: '防抖操作执行于',
      },
      table: {
        title: 'useTable 演示',
        description: '一个强大的表格 Hook，轻松管理分页、筛选、排序和选择逻辑。',
        search: '搜索',
        reset: '重置',
        total: '总计',
        prev: '上一页',
        next: '下一页',
        page: '/ 页',
        noData: '暂无数据',
        id: 'ID',
        name: '姓名',
        role: '角色',
        email: '邮箱',
        status: '状态',
      },
      form: {
        title: 'useForm 演示',
        description: '一个带有验证功能的综合表单管理 Hook。',
        username: '用户名',
        email: '邮箱',
        role: '角色',
        bio: '简介',
        submit: '提交',
        submitting: '提交中...',
        reset: '重置',
        success: '提交成功',
      },
      modal: {
        title: 'useModal & useDrawer 演示',
        description: '管理弹窗和抽屉的显示状态及参数。',
        openModal: '打开弹窗',
        openDrawer: '打开抽屉',
        modalTitle: '弹窗标题',
        drawerTitle: '抽屉标题',
        content: '这是一个使用 UnoCSS 类构建的弹窗。',
        drawerContent: '这是一个从右侧滑出的抽屉。',
        cancel: '取消',
        confirm: '确定',
        close: '关闭',
        save: '保存',
        params: '参数:',
      },
      permission: {
        title: 'usePermission 演示',
        description: '针对角色和操作的细粒度权限控制。',
        currentRole: '当前角色:',
        currentPerms: '当前权限:',
        toggle: '切换角色 (User ↔ Admin)',
        visibleAll: '所有人可见',
        visibleRead: "具有 'read' 权限可见 (v-if)",
        visibleWrite: "具有 'write' 权限可见 (v-if)",
        visibleDelete: "具有 'delete' 权限可见 (class hidden)",
      },
    },
    more: {
      title: '更多可用 Hooks',
      description: '这些 Hook 是库中包含的实用工具，但暂时没有独立的演示页面。',
      table: {
        name: 'Hook 名称',
        category: '分类',
        description: '描述',
      },
      hooks: {
        usePagination: '管理分页状态，支持页码和总数控制。',
        useClickOutside: '检测目标元素外部的点击事件。',
        useElementSize: '响应式获取 HTML 元素的尺寸。',
        useScroll: '响应式获取元素或窗口的滚动位置。',
        useEventListener: '注册事件监听器，并在组件卸载时自动清理。',
        useSessionStorage: '响应式 SessionStorage（API 与 useLocalStorage 一致）。',
        useThrottledRef: '用于频繁更新场景的节流响应式引用。',
        useGlobalState: '简单的全局状态管理，支持跨组件共享。',
        useMounted: 'onMounted 生命周期钩子的简写。',
        useUnmount: 'onUnmounted 生命周期钩子的简写。',
        useUpdate: '强制组件重新渲染。',
        useThrottleFn: '函数节流执行，限制触发频率。',
        useTimeoutFn: '延时执行函数，支持中途取消。',
        useRAF: 'Request Animation Frame 动画帧钩子。',
        useRouteGuard: 'Vue Router 导航守卫辅助函数。',
        useBreadcrumb: '管理面包屑导航状态。',
        useResponsive: '响应式断点助手（媒体查询）。',
      }
    },
    footer: {
      text: '基于 MIT 协议发布。',
    },
  },
}

export function useLanguage() {
  const t = computed(() => translations[currentLang.value])
  
  const toggleLanguage = () => {
    currentLang.value = currentLang.value === 'en' ? 'zh' : 'en'
  }

  return {
    currentLang,
    t,
    toggleLanguage,
  }
}
